fos_user:
  db_driver:      orm # can be orm or odm
  firewall_name:  admin
  user_class:     App\Entity\User
  group:
    group_class:   App\Entity\Group
  from_email:
    address: "g.ngandeu@it.afrikpay.com"
    sender_name: "Afrikpay"
