security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_SUBSCRIBE_USER: [ROLE_SUBSCRIBE]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                login_path: fos_user_security_login
                provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin
                always_use_default_target_path: true
            logout:
                handlers: [myapp_logoutListener]
                invalidate_session: false
                #path: fos_user_security_logout
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: ROLE_SUBSCRIBER }
        - { path: ^/manager, role: ROLE_MANAGER }
        - { path: ^/manager/, role: ROLE_MANAGER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
